controllers:
    resource: ../src/Controller/
    type: attribute
send_reset_email:
    path: /send-reset-email
    controller: App\Controller\PasswordResetController::sendResetEmail
    methods: POST
user_pdf:
  path: /userpdf
  controller: App\Controller\UserController::generatePdf