# config/services.yaml

parameters:
<<<<<<< HEAD
  profile_image_directory: "%kernel.project_dir%/public/uploads/profile_images"
  cours_pdf_directory: "%kernel.project_dir%/public/courspdf"

services:
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  # Explicitly registering the PasswordMatchValidator (optional, for clarity)
  App\Validator\PasswordMatchValidator:
    arguments: []
=======
    profile_image_directory: '%kernel.project_dir%/public/uploads/profile_images'
services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Explicitly registering the PasswordMatchValidator (optional, for clarity)
    App\Validator\PasswordMatchValidator:
        arguments: []
>>>>>>> f782c88b59be5afeb15030be249e2135611a9db9
